spark.eventLog.enabled=true
spark.eventLog.dir=s3a://crypto-analytics-lake-sj/spark-logs
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.InstanceProfileCredentialsProvider
spark.hadoop.com.amazonaws.services.s3.enableV4=true